/**
 * TransformerArchitecture.tsx
 * --------------------------------------------------------------------------------
 * Architecture Overview:
 * Interactive simulation of the complete Transformer Encoder-Decoder Architecture (Vaswani et al. 2017):
 *   - N = 6 Encoder Layers: Multi-Head Self-Attention + Position-wise FFN + Residual Add & Norm
 *   - N = 6 Decoder Layers: Masked Self-Attention + Encoder-Decoder Cross Attention + FFN + Add & Norm
 *
 * Sizing & Layout Polish:
 *   - Clean, compact sublayer buttons with inline formula tags.
 *   - Self-contained flexible layout that never clips or overflows on any viewport.
 *   - Auto-cycling dataflow pulse across Encoder and Decoder configurations.
 */

import React, { useState, useEffect } from 'react';
import { oneeBridge } from '../../lib/oneeEvents';
import { motion } from 'framer-motion';
import { Play, Pause, Layers, Zap, Sparkles, ShieldCheck, Cpu } from 'lucide-react';

interface SublayerInfo {
  id: string;
  name: string;
  formula: string;
  dim: string;
  description: string;
  color: string;
  bgLight: string;
  borderLight: string;
  icon: 'attention' | 'ffn' | 'cross' | 'mask';
}

export const TransformerArchitecture: React.FC = () => {
  const [activeStack, setActiveStack] = useState<'encoder' | 'decoder'>('encoder');
  const [activeSublayerIdx, setActiveSublayerIdx] = useState<number>(0);
  const [isPlaying, setIsPlaying] = useState<boolean>(true);

  const encoderSublayers: SublayerInfo[] = [
    {
      id: 'enc-input',
      name: '1. Input Embedding + Sinusoidal PE',
      formula: 'x_0 = Embedding(x) + PE_{(pos, 2i)}',
      dim: '512 dims',
      description: 'Continuous word embeddings combined with sinusoidal positional frequencies.',
      color: 'text-blue-600',
      bgLight: 'bg-blue-50/90',
      borderLight: 'border-blue-200',
      icon: 'attention'
    },
    {
      id: 'enc-mha',
      name: '2. Multi-Head Self-Attention (h=8)',
      formula: 'MultiHead(Q,K,V) = Concat(head_1..8)W^O',
      dim: 'd_k=64 per head',
      description: 'Allows tokens to attend to all other tokens across 8 parallel subspaces.',
      color: 'text-indigo-600',
      bgLight: 'bg-indigo-50/90',
      borderLight: 'border-indigo-200',
      icon: 'attention'
    },
    {
      id: 'enc-norm1',
      name: '3. Residual Connection + LayerNorm',
      formula: 'LayerNorm(x + Sublayer(x))',
      dim: 'd_model=512',
      description: 'Carries gradients directly through stack, preventing vanishing gradients in deep N=6 layers.',
      color: 'text-emerald-600',
      bgLight: 'bg-emerald-50/90',
      borderLight: 'border-emerald-200',
      icon: 'attention'
    },
    {
      id: 'enc-ffn',
      name: '4. Position-wise Feed-Forward Network',
      formula: 'FFN(x) = max(0, x W_1 + b_1)W_2 + b_2',
      dim: 'd_ff=2048',
      description: 'Two linear transformations with ReLU applied separately at each position.',
      color: 'text-amber-600',
      bgLight: 'bg-amber-50/90',
      borderLight: 'border-amber-200',
      icon: 'ffn'
    }
  ];

  const decoderSublayers: SublayerInfo[] = [
    {
      id: 'dec-mask',
      name: '1. Masked Multi-Head Self-Attention',
      formula: 'softmax(QKᵀ / √d_k + M)V',
      dim: 'Causal Mask',
      description: 'Prevents positions from attending to subsequent future tokens, preserving autoregression.',
      color: 'text-purple-600',
      bgLight: 'bg-purple-50/90',
      borderLight: 'border-purple-200',
      icon: 'mask'
    },
    {
      id: 'dec-cross',
      name: '2. Encoder-Decoder Cross Attention',
      formula: 'Q from Decoder, K & V from Encoder',
      dim: 'Source Context',
      description: 'Enables decoder to query full contextual representations generated by encoder stack.',
      color: 'text-pink-600',
      bgLight: 'bg-pink-50/90',
      borderLight: 'border-pink-200',
      icon: 'cross'
    },
    {
      id: 'dec-ffn',
      name: '3. Position-wise Feed-Forward & Residual',
      formula: 'FFN(x) + LayerNorm',
      dim: 'd_ff=2048',
      description: 'Processes cross-attention activations position-by-position before output projection.',
      color: 'text-amber-600',
      bgLight: 'bg-amber-50/90',
      borderLight: 'border-amber-200',
      icon: 'ffn'
    },
    {
      id: 'dec-out',
      name: '4. Linear Projection & Softmax Vocabulary',
      formula: 'P(y_t | y_{<t}) = softmax(x W_{vocab})',
      dim: 'Vocab ~37k',
      description: 'Converts final 512-dim continuous activations into predicted target token probabilities.',
      color: 'text-blue-600',
      bgLight: 'bg-blue-50/90',
      borderLight: 'border-blue-200',
      icon: 'ffn'
    }
  ];

  const currentSublayers = activeStack === 'encoder' ? encoderSublayers : decoderSublayers;
  const activeSublayer = currentSublayers[activeSublayerIdx % currentSublayers.length];

  // Auto-play dataflow cycle
  useEffect(() => {
    if (!isPlaying) return;

    const interval = setInterval(() => {
      setActiveSublayerIdx((prev) => {
        const next = (prev + 1) % currentSublayers.length;
        if (next === 0) {
          setActiveStack((curr) => (curr === 'encoder' ? 'decoder' : 'encoder'));
        }
        return next;
      });
    }, 2000);

    return () => clearInterval(interval);
  }, [isPlaying, currentSublayers.length]);

  const handleSelectSublayer = (idx: number) => {
    setActiveSublayerIdx(idx);
    const sub = currentSublayers[idx];
    oneeBridge.emit('slider_change', `“Inspecting ${sub.name}: ${sub.formula}”`);
  };

  const handleStackToggle = (stack: 'encoder' | 'decoder') => {
    setActiveStack(stack);
    setActiveSublayerIdx(0);
    oneeBridge.emit('chapter_change', `“Switched to Transformer ${stack.toUpperCase()} stack!”`);
  };

  const toggleAutoPlay = () => {
    setIsPlaying((prev) => !prev);
  };

  return (
    <div
      className="w-full h-full min-h-[200px] p-3 sm:p-4 rounded-3xl backdrop-blur-2xl bg-white/85 border border-white/60 shadow-apple-md flex flex-col justify-between font-sans overflow-hidden"
    >
      {/* Header & Control Bar */}
      <div className="flex items-center justify-between border-b border-black/5 pb-1.5 gap-1.5 shrink-0 flex-wrap">
        <div>
          <h3 className="text-xs sm:text-sm font-bold text-apple-text font-mono flex items-center gap-1.5">
            <span>Transformer Layer Reconstruction</span>
            <span className="text-[9px] font-mono text-apple-blue bg-blue-50 border border-blue-100 px-1.5 py-0.2 rounded-full font-bold">
              N=6 Stacks
            </span>
          </h3>
        </div>

        <div className="flex items-center gap-1.5 font-mono text-xs flex-wrap">
          {/* Auto-Flow Sweep Button */}
          <button
            onClick={toggleAutoPlay}
            className={`flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-bold transition-all shadow-apple-xs ${
              isPlaying
                ? 'bg-apple-blue text-white hover:bg-blue-600'
                : 'bg-slate-100 text-apple-secondary hover:text-apple-text hover:bg-slate-200'
            }`}
          >
            {isPlaying ? <Pause className="w-2.5 h-2.5" /> : <Play className="w-2.5 h-2.5 fill-current" />}
            <span>{isPlaying ? 'Auto-Flow Active' : 'Play Auto-Flow'}</span>
          </button>

          {/* Stack Switcher Pills */}
          <div className="flex items-center gap-0.5 bg-black/5 p-0.5 rounded-lg">
            <button
              onClick={() => handleStackToggle('encoder')}
              className={`px-2 py-0.5 rounded-md font-bold transition-all text-[10px] ${
                activeStack === 'encoder'
                  ? 'bg-white text-apple-blue shadow-apple-sm'
                  : 'text-apple-secondary hover:text-apple-text'
              }`}
            >
              Encoder
            </button>
            <button
              onClick={() => handleStackToggle('decoder')}
              className={`px-2 py-0.5 rounded-md font-bold transition-all text-[10px] ${
                activeStack === 'decoder'
                  ? 'bg-white text-apple-purple shadow-apple-sm'
                  : 'text-apple-secondary hover:text-apple-text'
              }`}
            >
              Decoder
            </button>
          </div>
        </div>
      </div>

      {/* Interactive Sublayer Tensor Flow Ladder */}
      <div className="my-auto py-1 space-y-1 flex-1 flex flex-col justify-center min-h-0">
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-1.5 w-full">
          {currentSublayers.map((sub, idx) => {
            const isSelected = idx === activeSublayerIdx;

            return (
              <motion.button
                key={sub.id}
                onClick={() => {
                  handleSelectSublayer(idx);
                }}
                whileHover={{ scale: 1.01 }}
                whileTap={{ scale: 0.99 }}
                animate={{
                  borderColor: isSelected ? '#0071e3' : 'rgba(0,0,0,0.06)',
                  boxShadow: isSelected ? '0 2px 8px rgba(0,113,227,0.15)' : 'none'
                }}
                className={`p-2 rounded-xl flex items-center justify-between font-mono text-xs transition-all border relative text-left ${
                  isSelected
                    ? `${sub.bgLight} border-apple-blue font-bold shadow-apple-xs`
                    : 'bg-slate-50 border-black/5 hover:bg-slate-100 text-apple-text'
                }`}
              >
                <div className="flex items-center gap-1.5 min-w-0">
                  {sub.icon === 'ffn' ? (
                    <Zap className={`w-3 h-3 shrink-0 ${isSelected ? sub.color : 'text-amber-500'}`} />
                  ) : (
                    <Layers className={`w-3 h-3 shrink-0 ${isSelected ? sub.color : 'text-apple-blue'}`} />
                  )}
                  <span className={`text-[10px] sm:text-[11px] truncate ${isSelected ? sub.color : 'text-apple-text'}`}>
                    {sub.name}
                  </span>
                </div>

                <span className="text-[9px] text-apple-secondary bg-white px-1.5 py-0.2 rounded border border-black/5 font-semibold shrink-0 ml-1">
                  {sub.dim}
                </span>
              </motion.button>
            );
          })}
        </div>

        {/* Selected Sublayer Mathematical Breakdown Card */}
        <motion.div
          key={activeSublayer.id}
          initial={{ opacity: 0, y: 2 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.2 }}
          className={`p-2 rounded-xl ${activeSublayer.bgLight} border ${activeSublayer.borderLight} space-y-0.5 shadow-apple-xs font-mono text-xs shrink-0 w-full`}
        >
          <div className="flex items-center justify-between flex-wrap gap-1">
            <div className="flex items-center gap-1 font-bold">
              <Sparkles className="w-3 h-3 text-apple-blue" />
              <span className={`text-[10px] sm:text-[11px] ${activeSublayer.color}`}>
                {activeSublayer.name}
              </span>
            </div>
            <span className="text-[9px] text-apple-text bg-white/90 px-1.5 py-0.2 rounded border border-black/5 font-mono font-semibold truncate">
              {activeSublayer.formula}
            </span>
          </div>

          <p className="text-apple-secondary text-[10px] font-sans leading-tight">
            {activeSublayer.description}
          </p>
        </motion.div>
      </div>

      {/* Architecture Specs Footer */}
      <div className="border-t border-black/5 pt-1 flex items-center justify-between text-[10px] font-mono text-apple-secondary flex-wrap gap-1 shrink-0">
        <div className="flex items-center gap-1">
          <ShieldCheck className="w-3 h-3 text-emerald-600" />
          <span>Residual: <strong className="text-apple-text font-bold">LayerNorm(x + SubLayer(x))</strong></span>
        </div>
        <div className="flex items-center gap-1 text-apple-blue font-semibold">
          <Cpu className="w-3 h-3" />
          <span>Shape: <strong className="text-apple-text">d_model=512, d_ff=2048</strong></span>
        </div>
      </div>
    </div>
  );
};

export default TransformerArchitecture;
